# Generated by Django 3.2.7 on 2021-09-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.category')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drinks.drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='drink',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='drinks.drink'),
            preserve_default=False,
        ),
    ]
